import type { ExperienceManifest, ParameterDef } from "../types";
import { updatePlayer } from "./player";
import { dispose, setup, tick } from "./scene";
import { applySettings } from "./settings";

const parameters: ParameterDef[] = [
	{
		id: "driftSpeed",
		label: "Drift Speed",
		group: "Movement",
		min: 0.5,
		max: 20,
		default: 2,
		step: 0.5,
		unit: "m/s",
		icon: "Gauge",
	},
	{
		id: "wasdSpeed",
		label: "Steig-/Drehrate",
		group: "Movement",
		min: 1,
		max: 20,
		default: 6,
		step: 0.5,
		unit: "m/s",
		icon: "ArrowUpDown",
	},
	{
		id: "lightIntensity",
		label: "Bioluminescence",
		group: "Atmosphere",
		min: 0.2,
		max: 3,
		default: 1.5,
		step: 0.1,
		icon: "Lightbulb",
	},
	{
		id: "terrainAmplitude",
		label: "Berg Höhe",
		group: "Terrain",
		min: 10,
		max: 70,
		default: 50,
		step: 2,
		unit: "m",
		icon: "Mountain",
	},
	{
		id: "terrainScale",
		label: "Berg Frequenz",
		group: "Terrain",
		min: 0.004,
		max: 0.04,
		default: 0.012,
		step: 0.002,
		icon: "Waves",
	},
	{
		id: "terrainColor",
		label: "Farbe Tönung",
		group: "Terrain",
		type: "color",
		min: 0,
		max: 1,
		default: "#ffffff",
		step: 1,
		icon: "Palette",
	},
	{
		id: "echolocationEnabled",
		label: "Echoortung",
		group: "Echoortung",
		type: "boolean",
		min: 0,
		max: 1,
		default: true,
		step: 1,
		icon: "Radio",
	},
	{
		id: "echolocationRange",
		label: "Scan-Reichweite",
		group: "Echoortung",
		min: 10,
		max: 120,
		default: 60,
		step: 5,
		unit: "m",
		icon: "Maximize",
	},
	{
		id: "echolocationInterval",
		label: "Scan-Intervall",
		group: "Echoortung",
		min: 0.5,
		max: 10,
		default: 3,
		step: 0.5,
		unit: "s",
		icon: "Timer",
	},
];

export const manifest: ExperienceManifest = {
	id: "underwater-world",
	name: "Underwater World V2",
	description:
		"Module underwater VR experience with bioluminescent life, procedural terrain, and echolocation.",
	version: "0.1.0",
	author: "Anastasia",

	parameters,
	outputs: [],
	interfaces: { orientation: true, speed: false },

	camera: { fov: 75, near: 0.1, far: 600 },
	scene: {
		background: "#001830",
		fogNear: 10,
		fogFar: 180,
		fogColor: "#001020",
		ambientIntensity: 0.5,
		sunIntensity: 0.8,
		sunColor: "#2288bb",
		sunPosition: { x: 0, y: 80, z: -50 },
	},
	spawn: { position: { x: 0, y: 4, z: 0 } },

	setup,
	tick,
	applySettings,
	updatePlayer,
	dispose,
};
