import type { ExperienceManifest, ParameterDef } from "../types";
import { updatePlayer } from "./player";
import { dispose, setup, tick } from "./scene";
import { applySettings } from "./settings";

const parameters: ParameterDef[] = [
	// ── Flight ──────────────────────────────────────────
	{
		id: "moveSpeed",
		label: "Move Speed",
		group: "Flight",
		min: 1,
		max: 20,
		default: 5,
		step: 0.5,
		unit: "m/s",
		icon: "Gauge",
	},
	{
		id: "smoothing",
		label: "Smoothing",
		group: "Flight",
		min: 0.02,
		max: 0.3,
		default: 0.08,
		step: 0.01,
		icon: "Activity",
	},

	// ── World ───────────────────────────────────────────
	{
		id: "cellSize",
		label: "Cell Size",
		group: "World",
		min: 10,
		max: 25,
		default: 20,
		step: 1,
		icon: "Box",
	},
	{
		id: "gyroidFreq",
		label: "Structure Density",
		group: "World",
		min: 0.05,
		max: 0.3,
		default: 0.15,
		step: 0.01,
		icon: "Waves",
	},
	{
		id: "wallThreshold",
		label: "Wall Threshold",
		group: "World",
		min: -0.5,
		max: 0.8,
		default: 0.1,
		step: 0.05,
		icon: "SlidersHorizontal",
	},
	{
		id: "hueShift",
		label: "Hue Shift",
		group: "World",
		min: 0,
		max: 360,
		default: 0,
		step: 5,
		unit: "\u00B0",
		icon: "Palette",
	},

	// ── Atmosphere ──────────────────────────────────────
	{
		id: "fogDistance",
		label: "Fog Distance",
		group: "Atmosphere",
		min: 50,
		max: 400,
		default: 220,
		step: 10,
		icon: "Cloud",
	},
	{
		id: "skySpeed",
		label: "Sky Animation",
		group: "Atmosphere",
		min: 0,
		max: 0.1,
		default: 0.01,
		step: 0.005,
		icon: "Wind",
	},
	{
		id: "sunElevation",
		label: "Sun Elevation",
		group: "Atmosphere",
		min: 0,
		max: 90,
		default: 25,
		step: 5,
		unit: "\u00B0",
		icon: "Sun",
	},

	// ── PostFX ──────────────────────────────────────────
	{
		id: "bloomIntensity",
		label: "Bloom",
		group: "PostFX",
		min: 0,
		max: 3,
		default: 1.8,
		step: 0.1,
		icon: "Sparkle",
	},
	{
		id: "grainIntensity",
		label: "Film Grain",
		group: "PostFX",
		min: 0,
		max: 0.5,
		default: 0.12,
		step: 0.01,
		icon: "Tv",
	},
	{
		id: "vignetteIntensity",
		label: "Vignette",
		group: "PostFX",
		min: 0,
		max: 1,
		default: 0.3,
		step: 0.05,
		icon: "Circle",
	},
	{
		id: "chromaticAberration",
		label: "Chromatic Aberration",
		group: "PostFX",
		min: 0,
		max: 0.005,
		default: 0.001,
		step: 0.0005,
		icon: "Sparkles",
	},
];

export const manifest: ExperienceManifest = {
	id: "gradient-prism",
	name: "Gradient Prism",
	description:
		"Fly through infinite gyroid architecture — corridors, rooms, and shafts of prismatic light",
	version: "3.0.0",
	author: "ICAROS Lab",
	thumbnail: "/experiences/gradient-prism/preview.webp",

	parameters,
	outputs: [],
	interfaces: { orientation: true, speed: true },

	camera: { fov: 75, near: 0.1, far: 800 },
	scene: {
		background: "#0d0025",
		fogNear: 15,
		fogFar: 220,
		fogColor: "#1a0a40",
		ambientIntensity: 0.6,
		sunIntensity: 1.2,
		sunColor: "#ffd4a0",
		sunPosition: { x: 60, y: 60, z: -30 },
	},
	spawn: { position: { x: 0, y: 10, z: 0 } },

	setup,
	tick,
	applySettings,
	updatePlayer,
	dispose,
};
