import type { ExperienceManifest, ParameterDef } from "../types";
import { updatePlayer } from "./player";
import { dispose, setup, tick } from "./scene";
import { applySettings } from "./settings";

const parameters: ParameterDef[] = [
	{
		id: "baseSpeed",
		label: "Base Speed",
		group: "Flight",
		min: 1,
		max: 30,
		default: 8,
		step: 1,
		unit: "m/s",
		icon: "Gauge",
	},
	{
		id: "rollYawMultiplier",
		label: "Roll-Yaw Sensitivity",
		group: "Flight",
		min: 0.5,
		max: 4,
		default: 1.5,
		step: 0.1,
		icon: "RotateCw",
	},
	{
		id: "lerpAlpha",
		label: "Smoothing",
		group: "Flight",
		min: 0.01,
		max: 0.5,
		default: 0.15,
		step: 0.01,
		icon: "Spline",
	},

	{
		id: "sunIntensity",
		label: "Sun Intensity",
		group: "Scene",
		min: 1,
		max: 5,
		default: 3,
		step: 0.1,
		icon: "Sun",
	},
	{
		id: "fogNear",
		label: "Fog Near",
		group: "Scene",
		min: 10,
		max: 100,
		default: 40,
		step: 1,
		icon: "CloudFog",
	},
	{
		id: "fogFar",
		label: "Fog Far",
		group: "Scene",
		min: 50,
		max: 300,
		default: 150,
		step: 1,
		icon: "Maximize",
	},
	{
		id: "fogColor",
		label: "Fog Color",
		group: "Scene",
		type: "color",
		min: 0,
		max: 1,
		default: "#a8d8ea",
		step: 1,
		icon: "Palette",
	},
	{
		id: "skyColorTop",
		label: "Sky Top",
		group: "Scene",
		type: "color",
		min: 0,
		max: 1,
		default: "#4a90d9",
		step: 1,
		icon: "Palette",
	},
	{
		id: "skyColorHorizon",
		label: "Sky Horizon",
		group: "Scene",
		type: "color",
		min: 0,
		max: 1,
		default: "#87ceeb",
		step: 1,
		icon: "Palette",
	},
	{
		id: "skyColorBottom",
		label: "Sky Bottom",
		group: "Scene",
		type: "color",
		min: 0,
		max: 1,
		default: "#e8f5e9",
		step: 1,
		icon: "Palette",
	},

	{
		id: "cloudCount",
		label: "Cloud Count",
		group: "Clouds",
		min: 5,
		max: 50,
		default: 20,
		step: 5,
		icon: "Cloud",
	},
	{
		id: "cloudOpacity",
		label: "Cloud Opacity",
		group: "Clouds",
		min: 0,
		max: 1,
		default: 0.8,
		step: 0.1,
		icon: "Cloud",
	},
	{
		id: "windSpeed",
		label: "Wind Speed",
		group: "Clouds",
		min: 0,
		max: 10,
		default: 2,
		step: 0.5,
		unit: "m/s",
		icon: "Wind",
	},

	{
		id: "grassHeight",
		label: "Grass Height",
		group: "Meadow",
		min: 0.5,
		max: 5,
		default: 2,
		step: 0.5,
		unit: "m",
		icon: "Sprout",
	},
	{
		id: "flowerDensity",
		label: "Flower Density",
		group: "Meadow",
		min: 0,
		max: 200,
		default: 60,
		step: 10,
		icon: "Flower2",
	},
	{
		id: "flowerColor",
		label: "Flower Color",
		group: "Meadow",
		type: "color",
		min: 0,
		max: 1,
		default: "#ff6b9d",
		step: 1,
		icon: "Palette",
	},
];

export const manifest: ExperienceManifest = {
	id: "insect-world",
	name: "Insect World",
	description: "Fliege als Insekt durch eine übergroße Wiesenwelt mit Gräsern, Blumen, Bächen und blauem Himmel",
	version: "0.1.0",
	author: "ICAROS Lab",
	thumbnail: "/experiences/insect-world/preview.webp",

	parameters,
	outputs: [],
	interfaces: { orientation: true, speed: true },

	camera: { fov: 75, near: 0.1, far: 500 },
	scene: {
		background: "#a8d8ea",
		fogNear: 40,
		fogFar: 150,
		fogColor: "#a8d8ea",
		ambientIntensity: 0.4,
		sunIntensity: 3.0,
		sunColor: "#fff4e0",
		sunPosition: { x: 50, y: 80, z: 30 },
	},
	spawn: { position: { x: 0, y: 2, z: 0 } },

	setup,
	tick,
	applySettings,
	updatePlayer,
	dispose,
};
